# Generated by Django 4.0.4 on 2022-04-19 20:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eventosdias',
            managers=[
                ('ativosG', django.db.models.manager.Manager()),
            ],
        ),
    ]
